### PR TITLE
Fix spontaneous crash during starting app in fullscreen mode on macOS.

### LINKED ISSUE #640: App starts in windowed mode even if WindowTraits::fullscreen was set to true on macOS
**Describe the bug**
App starts in windowed mode even if WindowTraits::fullscreen was set to true on macOS

**To Reproduce**
Try to create fullscreen app on macOS. App starts in windowed mode.

**Expected behavior**
App starts in fullscreen mode if WindowTraits::fullscreen set to true.

**Desktop (please complete the following information):**
- OS: Mac OS Ventura
- HW: Apple Silicon (M1)
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
- Target: arm64-apple-darwin22.1.0
- MoltenVK Vulkan SDK 1.3.231
- VulkanSceneGraph master

### PR DESCRIPTION
**Pull request by artemkulyk**
## Description
Switch to fullscreen mode was done before view is initialised. As a result, app can spontaneously crash on start in method handleFrameSizeChange.

Fixes #640

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested on local machine.

**Test Configuration**:
* OS: Mac OS Ventura
* HW: Apple Silicon (M1)
* Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
* Target: arm64-apple-darwin22.1.0
* MoltenVK Vulkan SDK 1.3.231
* VulkanSceneGraph master

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by robertosfield** [comment]
Is there a code example, or some docs that is guiding your changes that I can learn more about the topic?

**Comment by artemkulyk** [comment]
> Is there a code example, or some docs that is guiding your changes that I can learn more about the topic?

https://developer.apple.com/documentation/appkit/nswindowcollectionbehavior?language=objc
https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen?language=objc

Discussion of this topic:
https://stackoverflow.com/questions/24145269/how-to-begin-nswindow-in-fullscreen


With my previous change the app starts crashing on
https://github.com/vsg-dev/VulkanSceneGraph/blob/master/src/vsg/platform/macos/MacOS_Window.mm#L137.

I really don't know why previous changes worked at the beginning without crashing.

File: src/vsg/platform/macos/MacOS_Window.mm [hunk 1]
```diff
@@ -813,6 +809,14 @@ void createApplicationMenus(void)
     _window.initialFirstResponder = _view;
     [_window makeFirstResponder:_view];
 
+    if (traits->fullscreen)
+    {
+        NSRect screenFrame = [[NSScreen mainScreen] frame];
+        [_window setBackgroundColor: NSColor.whiteColor];
```
Comment (robertosfield) [inline src/vsg/platform/macos/MacOS_Window.mm:815]: Is this line required as there is a similar but not quite identical code on line 798 above.

Comment (artemkulyk) [reply src/vsg/platform/macos/MacOS_Window.mm:815]: Lines 814-815 are redundant and should be removed. It was blindly copy-pasted from the example.

Screenshot 2022-12-11 at 14 31 24

Comment (robertosfield) [reply src/vsg/platform/macos/MacOS_Window.mm]: Thanks for the clarification, I've removed the redundant line and will now merge.

What is the story behind the screenshot?

Comment (artemkulyk) [reply src/vsg/platform/macos/MacOS_Window.mm]: It's just vsgpagedlod example with static mapbox tiles and custom map style. By the way, vsg readers extract a file type from the file extension in the path from ```tileReader->imageLayer```. So it is not possible just to change the value of ```tileReader->imageLayer``` and experiment with 3rd party tile providers, like mapbox or HERE. mapbox and HERE tiles urls contain no file name with extension. It's confusing a little bit for newcomers. Possibly, it makes sense to extract file type from the server response instead of the file path.

Comment (robertosfield) [reply src/vsg/platform/macos/MacOS_Window.mm]: The vsg::tile ReaderWriter isn't intended to support all ways that tiles could be held on a server, it's a lightweight class that can handle some tile representations.  If a 3rd party source requires a query of supported formats from a server then I presume you'd need to formulate the query and way of mapping this to the final filename and extensions to sue then it'd need a new ReaderWriter that uses curl and as such would belong in vsgXchange.

Comment (robertosfield) [reply src/vsg/platform/macos/MacOS_Window.mm]: This type of discussion is best done within Discussions rather piggybacking off a PR.
