### PR TITLE
Fix error: invalid conversion from 'std::thread::native_handle_type' {aka 'unsigned int'} to 'HANDLE' {aka 'void*'}

### LINKED ISSUE #324: MinGW builds fail with `invalid conversion from 'std::thread::native_handle_type' {aka 'unsigned int'} to 'HANDLE' {aka 'void*'}`
**Describe the bug**
Building vsg with MinGW gcc fails with the mentioned error

**To Reproduce**
This issue has been detected at https://build.opensuse.org/package/show/home:rhabacker:branches:games:mingw32/mingw32-libvsg

**Expected behavior**
The build should not fail

### PR DESCRIPTION
**Pull request by rhabacker**
## Description
The commit from this pr fixes a build error with MinGW gcc 
Fixes #324

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
The vsg library was build with this patch applied at https://build.opensuse.org/package/show/home:rhabacker:branches:games:mingw32/mingw32-libvsg

**Test Configuration**:
* Toolchain: MinGW gcc 
* SDK: vsg git master branch

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/vsg/threading/Affinity.cpp [hunk 1]
```diff
@@ -46,7 +46,7 @@ static void win32_setAffinity(HANDLE tid, const vsg::Affinity& affinity)
 
 void vsg::setAffinity(std::thread& thread, const Affinity& affinity)
 {
-    win32_setAffinity(thread.native_handle(), affinity);
+    win32_setAffinity((HANDLE)thread.native_handle(), affinity);
```
Comment (robertosfield) [inline src/vsg/threading/Affinity.cpp:49]: Would be better to use a static_cast<HANDLE>(thread).  Could you try this and see if it builds OK?

Comment (rhabacker) [reply src/vsg/threading/Affinity.cpp]: No, now I get 
```
[  123s] /home/abuild/rpmbuild/BUILD/VulkanSceneGraph-0.1.4.20210909.git+7847d18a/src/vsg/threading/Affinity.cpp: In function 'void vsg::setAffinity(std::thread&, const vsg::Affinity&)':
[  123s] /home/abuild/rpmbuild/BUILD/VulkanSceneGraph-0.1.4.20210909.git+7847d18a/src/vsg/threading/Affinity.cpp:49:65: error: invalid static_cast from type 'std::thread::native_handle_type' {aka 'unsigned int'} to type 'HANDLE' {aka 'void*'}
[  123s]    49 |     win32_setAffinity(static_cast<HANDLE>(thread.native_handle()), affinity);
[  123s]       |                                                                 ^
[  123s] make[2]: *** [src/vsg/CMakeFiles/vsg.dir/build.make:1498: src/vsg/CMakeFiles/vsg.dir/threading/Affinity.cpp.obj] Error 1
[  123s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/VulkanSceneGraph-0.1.4.20210909.git+7847d18a'
[  123s] make[2]: *** Waiting for unfinished jobs....
```
