### PR TITLE
Mingw fixes

### LINKED ISSUE #649: MinGW compiler was excluded for file related functions
**Describe the bug**
With commit https://github.com/vsg-dev/VulkanSceneGraph/commit/f1557223d050f386d2ed473c0300184d3f886250 several places were changed so that they are only activated when using a msvc compiler. These are the definition of the path separator and Windows-specific wide character and security-related functions. In the first case this leads to runtime errors, because paths are no longer separated correctly.  In the other cases, less secure and restricted functions are used.

**To Reproduce**
1. Inspect https://github.com/vsg-dev/VulkanSceneGraph/blob/affebd1aae1ccf71ab50a4d583b7e3ed2fe35f57/src/vsg/io/FileSystem.cpp#L55, which is only enabled when using msvc compiler.
2. Inspect https://github.com/vsg-dev/VulkanSceneGraph/commit/f1557223d050f386d2ed473c0300184d3f886250#diff-fde3bc681bc65905ab9792631af9ac2886ae7ca65228e4f83677cc0f508e1d3fR77, where the getenv_s function is not used with MinGW
3. Inspect https://github.com/vsg-dev/VulkanSceneGraph/commit/f1557223d050f386d2ed473c0300184d3f886250#diff-fde3bc681bc65905ab9792631af9ac2886ae7ca65228e4f83677cc0f508e1d3fR109 where a limited function is used.

**Expected behavior**
1. The path separator ';' should be used also when compiling vsg with MinGW.
2. The mentioned functions should be also used when compiling with MinGW

**Desktop (please complete the following information):**
 - OS: openSUSE
 - Version: Leap 15.4
 - MinGW header/libraries version 10
 - MinGW C++ Compiler 12.2

### PR DESCRIPTION
**Pull request by rhabacker**
# Pull Request Template

## Description
Readd MinGW support for wide/safe file related functions

Fixes #649

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Build vsg with the associated commits
- [x] Build osg2vsg with an installed vsg and changes https://github.com/vsg-dev/osg2vsg/pull/79 applied

**Test Configuration**:
* Hardware: NVIDIA GTX 1070
* Toolchain: MinGW C++ Compiler 12
* SDK: MinGW header/libraries 10

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules (see https://github.com/vsg-dev/osg2vsg/pull/79)

### CODE REVIEW

File: src/vsg/io/VSG.cpp [hunk 1]
```diff
@@ -99,7 +99,7 @@ vsg::ref_ptr<vsg::Object> VSG::read(const vsg::Path& filename, ref_ptr<const Opt
         vsg::Path filenameToUse = findFile(filename, options);
         if (!filenameToUse) return {};
 
-        std::ifstream fin(filenameToUse, std::ios::in | std::ios::binary);
+        std::ifstream fin(filenameToUse.c_str(), std::ios::in | std::ios::binary);
```
Comment (robertosfield) [inline src/vsg/io/VSG.cpp:102]: I presume the Ming std::ifstream must be missing a (wstring&) constructor. Would adding a vsg::Path operator:

        inline operator const value_type* () const noexcept { return _string.c_str(); }

work?

I think this might be preferable to updating lots of VSG and associated project code  for just MinGW.

**Comment by robertosfield** [comment]
I have created a Path_operator_change for the VSG and vsgExamples:

https://github.com/vsg-dev/VulkanSceneGraph/tree/Path_operator_change
https://github.com/vsg-dev/vsgExamples/tree/Path_operator_change

This builds under Kubuntu 22.04, and I presume other unix platforms.  @rhabacker could you try this branch out as a base for your MinGW changes.  Also if you have a VS compiler could you check that it also compiles OK.  If things look OK I cam merge this branch with master then look at applying your MinGW changes.

**Comment by robertosfield** [comment]
Unfortunately my [Path_operator_change](https://github.com/vsg-dev/VulkanSceneGraph/tree/Path_operator_change) changes are failing to build on Android:

https://github.com/vsg-dev/VulkanSceneGraph/actions/runs/3675681499/jobs/6215402078

Argghgh...

**Comment by rhabacker** [comment]
> Unfortunately my [Path_operator_change](https://github.com/vsg-dev/VulkanSceneGraph/tree/Path_operator_change) changes are failing to build on Android:
> 
> https://github.com/vsg-dev/VulkanSceneGraph/actions/runs/3675681499/jobs/6215402078
> 
> Argghgh...

I got build success on linux and MinGW by limiting the new operator to mingw builds

    #if defined(__MINGW32__)
        inline operator const value_type* () const noexcept { return _string.c_str(); }
    #endif

**Comment by rhabacker** [comment]
>  Also if you have a VS compiler could you check that it also compiles OK.

I don't have a local msvc compiler, but the CI has an msvc build job.
